In [7]:
import sklearn
import pandas
import numpy as np
import matplotlib

In [ ]:
lista = [1, 2, 3, 4]

array = np.array(lista)

In [ ]:
arr_zeros = np.zeros(10) # array com 10 zeros

In [8]:
# matrizes
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# notas de aluno
lista_notas = [9.8, 5.6, 7.8, 6.5, 9.1]

notas = np.array(lista_notas)

In [13]:
print(f"Maximo {notas.max()}")
print(f"Minimo {notas.min()}")
print(f"Desvio padrão {notas.std()}")
print(f"Media {notas.mean()}")
print(f"Posição menor {notas.argmin()}")
print(f"")

Maximo 9.8
Minimo 5.6
Desvio padrão 1.5628179676469045
Media 7.76
Posição menor 1

